baseURL       : http://localhost:1313/
title         : OverArizona
languageCode  : en-us

params:

  description	  : A travelogue of people, places &amp; things that make Arizona unique, featuring exclusive aerial imagery, photography and history

# Navigation ============================================================================
navigation:
  