baseURL       : http://example.org/
languageCode  : "en-us"
title         : OverArizona

preserveTaxonomyNames : true
paginate              : 5
disqusShortname       : ""
googleAnalytics       : ""
pluralizeListTitles   : false

contentDir            : "content"

enableRobotsTXT       : true

disableHugoGeneratorInject: true

params:
  description : A travelogue of people, places, & things that make Arizona unique. From spectacular landscapes & colorful history, to the fascinating culture & endless adventure.
  logo        : OAZ-logo-120px.png
  logoalt     : OverArizona logo

  imgCDN      : https://ik.imagekit.io/overarizona/

  # Social media links: Use font class names --------------------------------------------
  socialmedia:
  # - name: flickr
    # link:
  # - name: medium
    # link:
  - name: flaticon-linkedin
    link: https://www.linkedin.com/company/overarizona
  # - name: youtube
    # link:
  - name: flaticon-vimeo-letter-logo-in-a-square
    link:
  - name: flaticon-instagram-photo-camera-symbol
    link: "https://www.instagram.com/overarizona/"
